(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          START_TIME-VAL
          START_TIME
          FINAL_TIME-VAL
          FINAL_TIME
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          ACTION-VAL
          ACTION
          K-VAL
          K
          K_MAX-VAL
          K_MAX
          A-VAL
          A
          B-VAL
          B
          S-VAL
          S
          TIME-VAL
          TIME
          TIME_ACC-VAL
          TIME_ACC
          S_STEP-VAL
          S_STEP
          DEBUG_INFO-VAL
          DEBUG_INFO
))