(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          START_VELOCITY-VAL
          START_VELOCITY
          START_ACCELERATION-VAL
          START_ACCELERATION
          PLAN_POINTS-VAL
          PLAN_POINTS
          CHECK_POINTS-VAL
          CHECK_POINTS
          STOP_VELOCITY-VAL
          STOP_VELOCITY
          STOP_ACCELERATION-VAL
          STOP_ACCELERATION
          REPLAN_TIME_LENGTH-VAL
          REPLAN_TIME_LENGTH
          CHECK_POINTS_TIME_INTERVAL-VAL
          CHECK_POINTS_TIME_INTERVAL
          PLAN_POINTS_TIME_INTERVAL-VAL
          PLAN_POINTS_TIME_INTERVAL
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          REPLAN_TO_GLOBAL_TIME-VAL
          REPLAN_TO_GLOBAL_TIME
))