(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          ACTION-VAL
          ACTION
          NUM_ORDER-VAL
          NUM_ORDER
          NUM_SEGMENT-VAL
          NUM_SEGMENT
          START_YAW-VAL
          START_YAW
          FINAL_YAW-VAL
          FINAL_YAW
          COEF_X-VAL
          COEF_X
          COEF_Y-VAL
          COEF_Y
          COEF_Z-VAL
          COEF_Z
          TIME-VAL
          TIME
          MAG_COEFF-VAL
          MAG_COEFF
          ORDER-VAL
          ORDER
          DEBUG_INFO-VAL
          DEBUG_INFO
))