(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          START_TIME-VAL
          START_TIME
          FINAL_TIME-VAL
          FINAL_TIME
          TRAJECTORY_ID-VAL
          TRAJECTORY_ID
          ACTION-VAL
          ACTION
          K-VAL
          K
          K_MAX-VAL
          K_MAX
          A-VAL
          A
          B-VAL
          B
          S-VAL
          S
          TIME-VAL
          TIME
          TIME_ACC-VAL
          TIME_ACC
          S_STEP-VAL
          S_STEP
          NUM_ORDER-VAL
          NUM_ORDER
          NUM_SEGMENT-VAL
          NUM_SEGMENT
          START_YAW-VAL
          START_YAW
          FINAL_YAW-VAL
          FINAL_YAW
          COEF_X-VAL
          COEF_X
          COEF_Y-VAL
          COEF_Y
          COEF_Z-VAL
          COEF_Z
          RANGE-VAL
          RANGE
          MAG_COEFF-VAL
          MAG_COEFF
          ORDER-VAL
          ORDER
          DEBUG_INFO-VAL
          DEBUG_INFO
))